import { Branch, ProductCategory, Product, Story, Event, PhotoUpload } from "../types";

export const MOCK_BRANCHES: Branch[] = [
  {
    branchId: "branch-baturaja-01",
    name: "Raccoon Coffee Baturaja",
    address: "Bakung, Baturaja",
    city: "Baturaja",
    postalCode: null,
    openingTime: "13:00",
    closingTime: "23:00",
    phone: null,
    mapsUrl: "https://maps.google.com/?q=Raccoon+Coffee+Baturaja",
    isActive: true,
  },
];

export const MOCK_CATEGORIES: ProductCategory[] = [
  { categoryId: "cat-coffee", name: "Kopi Susu & Espresso", slug: "kopi-susu-espresso", displayOrder: 1 },
  { categoryId: "cat-milk", name: "Milky Beverages", slug: "milky-beverages", displayOrder: 2 },
  { categoryId: "cat-non", name: "Bukan Kopi", slug: "bukan-kopi", displayOrder: 3 },
  { categoryId: "cat-bites", name: "Teman Ngopi", slug: "teman-ngopi", displayOrder: 4 },
];

export const MOCK_PRODUCTS: Product[] = [
  // Coffee – cat-coffee – 8 items
  {
    productId: "prod-coffee-espresso",
    name: "Espresso",
    slug: "espresso",
    categoryId: "cat-coffee",
    description: "Espresso.",
    price: "24000.00",
    imageUrl: "/images/raccoon/menu/coffee/espresso.jpg",
    status: "ACTIVE",
    displayOrder: 1,
  },
  {
    productId: "prod-coffee-americano",
    name: "Americano",
    slug: "americano",
    categoryId: "cat-coffee",
    description: "Espresso, air panas.",
    price: "26000.00",
    imageUrl: "/images/raccoon/menu/coffee/americano.jpg",
    status: "ACTIVE",
    displayOrder: 2,
  },
  {
    productId: "prod-coffee-pourover",
    name: "Pour Over",
    slug: "pour-over",
    categoryId: "cat-coffee",
    description: "Kopi seduh manual.",
    price: "42000.00",
    imageUrl: "/images/raccoon/menu/coffee/pourover.jpg",
    status: "ACTIVE",
    displayOrder: 3,
  },
  {
    productId: "prod-coffee-beans",
    name: "Coffee Beans",
    slug: "coffee-beans",
    categoryId: "cat-coffee",
    description: "Kopi dalam kemasan 250 g.",
    price: "45000.00",
    imageUrl: "/images/raccoon/menu/coffee/beans.jpg",
    status: "ACTIVE",
    displayOrder: 4,
  },
  {
    productId: "prod-coffee-coldbrew",
    name: "Cold Brew",
    slug: "cold-brew",
    categoryId: "cat-coffee",
    description: "Kopi dingin.",
    price: "38000.00",
    imageUrl: "/images/raccoon/menu/coffee/coldbrew.jpg",
    status: "ACTIVE",
    displayOrder: 5,
  },
  {
    productId: "prod-coffee-mocha",
    name: "Mocha",
    slug: "mocha",
    categoryId: "cat-coffee",
    description: "Espresso, cokelat, dan susu.",
    price: "36000.00",
    imageUrl: "/images/raccoon/menu/coffee/mocha.jpg",
    status: "ACTIVE",
    displayOrder: 6,
  },
  {
    productId: "prod-coffee-latte",
    name: "Latte",
    slug: "latte",
    categoryId: "cat-coffee",
    description: "Espresso, susu panas.",
    price: "35000.00",
    imageUrl: "/images/raccoon/menu/coffee/latte.jpg",
    status: "ACTIVE",
    displayOrder: 7,
  },
  {
    productId: "prod-coffee-cappuccino",
    name: "Cappuccino",
    slug: "cappuccino",
    categoryId: "cat-coffee",
    description: "Espresso, busa tipis.",
    price: "35000.00",
    imageUrl: "/images/raccoon/menu/coffee/cappuccino.jpg",
    status: "ACTIVE",
    displayOrder: 8,
  },
  // Milk – cat-milk – 5 items
  {
    productId: "prod-milk-strawberry",
    name: "Strawberry Milk",
    slug: "strawberry-milk",
    categoryId: "cat-milk",
    description: "Susunya segar.",
    price: "32000.00",
    imageUrl: "/images/raccoon/menu/milk/strawberry.jpg",
    status: "ACTIVE",
    displayOrder: 1,
  },
  {
    productId: "prod-milk-chocolate",
    name: "Chocolate Milk",
    slug: "chocolate-milk",
    categoryId: "cat-milk",
    description: "Susu cokelat.",
    price: "32000.00",
    imageUrl: "/images/raccoon/menu/milk/chocolate.jpg",
    status: "ACTIVE",
    displayOrder: 2,
  },
  {
    productId: "prod-milk-vanilla",
    name: "Vanilla Milk",
    slug: "vanilla-milk",
    categoryId: "cat-milk",
    description: "Susu vanila.",
    price: "32000.00",
    imageUrl: "/images/raccoon/menu/milk/vanilla.jpg",
    status: "ACTIVE",
    displayOrder: 3,
  },
  {
    productId: "prod-milk-fresh",
    name: "Fresh Milk",
    slug: "fresh-milk",
    categoryId: "cat-milk",
    description: "Susu segar.",
    price: "28000.00",
    imageUrl: "/images/raccoon/menu/milk/fresh.jpg",
    status: "ACTIVE",
    displayOrder: 4,
  },
  {
    productId: "prod-milk-creamy",
    name: "Creamy Milk",
    slug: "creamy-milk",
    categoryId: "cat-milk",
    description: "Susu kental.",
    price: "34000.00",
    imageUrl: "/images/raccoon/menu/milk/creamy.jpg",
    status: "ACTIVE",
    displayOrder: 5,
  },
  // Non-Coffee – cat-non – 5 items
  {
    productId: "prod-non-matcha",
    name: "Matcha",
    slug: "matcha",
    categoryId: "cat-non",
    description: "Matcha, susu, dan manis.",
    price: "33500.00",
    imageUrl: "/images/raccoon/menu/noncoffee/matcha.jpg",
    status: "ACTIVE",
    displayOrder: 1,
  },
  {
    productId: "prod-non-tea",
    name: "Tea",
    slug: "tea",
    categoryId: "cat-non",
    description: "Teh hitam.",
    price: "25000.00",
    imageUrl: "/images/raccoon/menu/noncoffee/tea.jpg",
    status: "ACTIVE",
    displayOrder: 2,
  },
  {
    productId: "prod-non-lemon-tea",
    name: "Lemon Tea",
    slug: "lemon-tea",
    categoryId: "cat-non",
    description: "Teh lemon.",
    price: "26000.00",
    imageUrl: "/images/raccoon/menu/noncoffee/lemon-tea.jpg",
    status: "ACTIVE",
    displayOrder: 3,
  },
  {
    productId: "prod-non-chocolate",
    name: "Chocolate",
    slug: "chocolate",
    categoryId: "cat-non",
    description: "Cokelat panas.",
    price: "27500.00",
    imageUrl: "/images/raccoon/menu/noncoffee/chocolate.jpg",
    status: "ACTIVE",
    displayOrder: 4,
  },
  {
    productId: "prod-non-iced",
    name: "Iced Non-Coffee",
    slug: "iced-non-coffee",
    categoryId: "cat-non",
    description: "Iced non-coffee beverage.",
    price: "28000.00",
    imageUrl: "/images/raccoon/menu/noncoffee/iced.jpg",
    status: "ACTIVE",
    displayOrder: 5,
  },
  // Bites – cat-bites – unchanged
  {
    productId: "prod-5",
    name: "Roti Bakar Kaya Butter",
    slug: "roti-bakar-kaya-butter",
    categoryId: "cat-bites",
    description: "Roti panggang.",
    price: "32000.00",
    imageUrl: "/images/menu-5.svg",
    status: "ACTIVE",
    displayOrder: 5,
  },
  {
    productId: "prod-6",
    name: "Cinnamon Roll Hangat",
    slug: "cinnamon-roll-hangat",
    categoryId: "cat-bites",
    description: "Roti manis.",
    price: "30000.00",
    imageUrl: "/images/menu-6.svg",
    status: "ACTIVE",
    displayOrder: 6,
  },
];

export const MOCK_STORIES: Story[] = [
  {
    storyId: "story-1",
    title: "Coffee and Chill di Baturaja",
    slug: "coffee-and-chill-di-baturaja",
    content: "Raccoon Coffee Baturaja adalah tempat untuk ngopi, makan, dan bersantai di Bakung, Baturaja. Buka Selasa–Minggu, 13.00–23.00.",
    coverImageUrl: "/images/raccoon/atmosphere/interior.jpg",
    status: "PUBLISHED",
    publishedAt: null,
  },
];

export const MOCK_EVENTS: Event[] = [];

export const MOCK_PHOTOS: PhotoUpload[] = [
  {
    photoId: "photo-1",
    visitorName: "",
    caption: null,
    imageUrl: "/images/raccoon/wall/morning.jpg",
    thumbnailUrl: null,
    status: "APPROVED",
    createdAt: "2026-10-04T09:12:00Z",
  },
  {
    photoId: "photo-2",
    visitorName: "",
    caption: null,
    imageUrl: "/images/raccoon/wall/conversation.jpg",
    thumbnailUrl: null,
    status: "APPROVED",
    createdAt: "2026-10-03T14:20:00Z",
  },
  {
    photoId: "photo-3",
    visitorName: "",
    caption: null,
    imageUrl: "/images/raccoon/wall/cafe-moment.jpg",
    thumbnailUrl: null,
    status: "APPROVED",
    createdAt: "2026-10-02T11:05:00Z",
  },
  {
    photoId: "photo-4",
    visitorName: "",
    caption: null,
    imageUrl: "/images/raccoon/wall/friends.jpg",
    thumbnailUrl: null,
    status: "APPROVED",
    createdAt: "2026-10-01T16:45:00Z",
  },
  {
    photoId: "photo-5",
    visitorName: "",
    caption: null,
    imageUrl: "/images/raccoon/wall/candid.jpg",
    thumbnailUrl: null,
    status: "APPROVED",
    createdAt: "2026-09-30T08:30:00Z",
  },
  {
    photoId: "photo-6",
    visitorName: "",
    caption: null,
    imageUrl: "/images/raccoon/wall/coffee-date.jpg",
    thumbnailUrl: null,
    status: "APPROVED",
    createdAt: "2026-09-29T15:10:00Z",
  },
  {
    photoId: "photo-7",
    visitorName: "",
    caption: null,
    imageUrl: "/images/raccoon/wall/laughing.jpg",
    thumbnailUrl: null,
    status: "APPROVED",
    createdAt: "2026-09-28T13:40:00Z",
  },
  {
    photoId: "photo-8",
    visitorName: "",
    caption: null,
    imageUrl: "/images/raccoon/wall/group.jpg",
    thumbnailUrl: null,
    status: "APPROVED",
    createdAt: "2026-09-27T10:15:00Z",
  },
];
